#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BFL_PlatformUIData

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "Backrooms_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BFL_PlatformUIData.BFL_PlatformUIData_C
// 0x0000 (0x0028 - 0x0028)
class UBFL_PlatformUIData_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetRichImageText(class FName InputName, class UObject* __WorldContext, class FText* RichText);
	static void GetInputActionKeyName(const class FName ActionName, class UObject* __WorldContext, class FText* Name_0);
	static void GetKeybindByInputName(class FName InputName, class UObject* __WorldContext, class FText* Name_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BFL_PlatformUIData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BFL_PlatformUIData_C")
	}
	static class UBFL_PlatformUIData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBFL_PlatformUIData_C>();
	}
};
DUMPER7_ASSERTS_UBFL_PlatformUIData_C;

}

