#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Card

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Card.BP_Card_C.ToggleVisibility
// 0x0002 (0x0002 - 0x0000)
struct BP_Card_C_ToggleVisibility final
{
public:
	bool                                          IsVisible_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_Card_C_ToggleVisibility;

// Function BP_Card.BP_Card_C.OnRep_PlayerName
// 0x0030 (0x0030 - 0x0000)
struct BP_Card_C_OnRep_PlayerName final
{
public:
	class FText                                   CallFunc_Conv_NameToText_ReturnValue;              // 0x0000(0x0018)()
	class UUserWidget*                            CallFunc_GetWidget_ReturnValue;                    // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCard_UI_C*                             K2Node_DynamicCast_AsCard_UI;                      // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_Card_C_OnRep_PlayerName;

// Function BP_Card.BP_Card_C.OnRep_IsVisible
// 0x0018 (0x0018 - 0x0000)
struct BP_Card_C_OnRep_IsVisible final
{
public:
	class AActor*                                 CallFunc_GetAttachParentActor_ReturnValue;         // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABPCharacter_Demo_C*                    K2Node_DynamicCast_AsBPCharacter_Demo;             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_Card_C_OnRep_IsVisible;

}

