#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChunkActor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_ChunkActor.BP_ChunkActor_C.ExecuteUbergraph_BP_ChunkActor
// 0x0004 (0x0004 - 0x0000)
struct BP_ChunkActor_C_ExecuteUbergraph_BP_ChunkActor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ChunkActor_C_ExecuteUbergraph_BP_ChunkActor;

// Function BP_ChunkActor.BP_ChunkActor_C.UserConstructionScript
// 0x0001 (0x0001 - 0x0000)
struct BP_ChunkActor_C_UserConstructionScript final
{
public:
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_ChunkActor_C_UserConstructionScript;

}

