#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_AlmondBottle

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Item_AlmondBottle.BP_Item_AlmondBottle_C.SetMaterial
// 0x0001 (0x0001 - 0x0000)
struct BP_Item_AlmondBottle_C_SetMaterial final
{
public:
	bool                                          EnabledFOV;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_Item_AlmondBottle_C_SetMaterial;

}

