#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Card_UI

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Card_UI.Card_UI_C
// 0x0020 (0x0280 - 0x0260)
class UCard_UI_C final : public UUserWidget
{
public:
	class UImage*                                 Image_90;                                          // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_233;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             NameText;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             NameText_1;                                        // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetName(const class FText& Name_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Card_UI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Card_UI_C")
	}
	static class UCard_UI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCard_UI_C>();
	}
};
DUMPER7_ASSERTS_UCard_UI_C;

}

