#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClimbLadderSequence

#include "Basic.hpp"


namespace SDK::Params
{

// Function ClimbLadderSequence.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// 0x0004 (0x0004 - 0x0000)
struct ClimbLadderSequence_SequenceDirector_C_ExecuteUbergraph_SequenceDirector final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
//DUMPER7_ASSERTS_ClimbLadderSequence_SequenceDirector_C_ExecuteUbergraph_SequenceDirector;

}

