#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FadeOutLevelStart_UI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FadeOutLevelStart_UI.FadeOutLevelStart_UI_C
// 0x0020 (0x0280 - 0x0260)
class UFadeOutLevelStart_UI_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeIn;                                            // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Fade;                                              // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	bool                                          Reverse;                                           // 0x0278(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_FadeOutLevelStart_UI(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FadeOutLevelStart_UI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FadeOutLevelStart_UI_C")
	}
	static class UFadeOutLevelStart_UI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFadeOutLevelStart_UI_C>();
	}
};
DUMPER7_ASSERTS_UFadeOutLevelStart_UI_C;

}

