#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GM_MainMenu

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GM_MainMenu.GM_MainMenu_C
// 0x0008 (0x02C8 - 0x02C0)
class AGM_MainMenu_C final : public AGameModeBase
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GM_MainMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GM_MainMenu_C")
	}
	static class AGM_MainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGM_MainMenu_C>();
	}
};
DUMPER7_ASSERTS_AGM_MainMenu_C;

}

