#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MagicLeapHandTracking

#include "Basic.hpp"

#include "LiveLinkInterface_classes.hpp"
#include "MagicLeapHandTracking_structs.hpp"
#include "Engine_classes.hpp"
#include "InputCore_structs.hpp"


namespace SDK
{

// Class MagicLeapHandTracking.LiveLinkMagicLeapHandTrackingSourceFactory
// 0x0000 (0x0028 - 0x0028)
class ULiveLinkMagicLeapHandTrackingSourceFactory final : public ULiveLinkSourceFactory
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LiveLinkMagicLeapHandTrackingSourceFactory")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LiveLinkMagicLeapHandTrackingSourceFactory")
	}
	static class ULiveLinkMagicLeapHandTrackingSourceFactory* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveLinkMagicLeapHandTrackingSourceFactory>();
	}
};
DUMPER7_ASSERTS_ULiveLinkMagicLeapHandTrackingSourceFactory;

// Class MagicLeapHandTracking.MagicLeapHandTrackingFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UMagicLeapHandTrackingFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool GetConfiguration(TArray<EMagicLeapHandTrackingGesture>* ActiveStaticGestures, EMagicLeapHandTrackingKeypointFilterLevel* KeypointsFilterLevel, EMagicLeapHandTrackingGestureFilterLevel* GestureFilterLevel, bool* bTrackingEnabled);
	static bool GetCurrentGesture(EControllerHand hand, EMagicLeapHandTrackingGesture* Gesture);
	static bool GetCurrentGestureConfidence(EControllerHand hand, float* Confidence);
	static bool GetGestureKeypoints(EControllerHand hand, TArray<struct FTransform>* Keypoints);
	static bool GetGestureKeypointTransform(EControllerHand hand, EMagicLeapHandTrackingKeypoint Keypoint, EMagicLeapGestureTransformSpace TransformSpace, struct FTransform* Transform);
	static bool GetHandCenter(EControllerHand hand, struct FTransform* HandCenter);
	static bool GetHandCenterNormalized(EControllerHand hand, struct FVector* HandCenterNormalized);
	static bool GetHandIndexFingerTip(EControllerHand hand, EMagicLeapGestureTransformSpace TransformSpace, struct FTransform* Pointer);
	static bool GetHandKeypointForMotionSource(class FName MotionSource, EMagicLeapHandTrackingKeypoint* OutKeyPoint);
	static bool GetHandThumbTip(EControllerHand hand, EMagicLeapGestureTransformSpace TransformSpace, struct FTransform* Secondary);
	static bool GetMagicLeapHandTrackingLiveLinkSource(struct FLiveLinkSourceHandle* SourceHandle);
	static bool GetMotionSourceForHandKeypoint(EControllerHand hand, EMagicLeapHandTrackingKeypoint Keypoint, class FName* OutMotionSource);
	static float GetStaticGestureConfidenceThreshold(EMagicLeapHandTrackingGesture Gesture);
	static bool IsHoldingControl(EControllerHand hand);
	static bool SetConfiguration(const TArray<EMagicLeapHandTrackingGesture>& StaticGesturesToActivate, EMagicLeapHandTrackingKeypointFilterLevel KeypointsFilterLevel, EMagicLeapHandTrackingGestureFilterLevel GestureFilterLevel, bool bTrackingEnabled);
	static void SetStaticGestureConfidenceThreshold(EMagicLeapHandTrackingGesture Gesture, float Confidence);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagicLeapHandTrackingFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagicLeapHandTrackingFunctionLibrary")
	}
	static class UMagicLeapHandTrackingFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMagicLeapHandTrackingFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UMagicLeapHandTrackingFunctionLibrary;

}

