#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OpenInputPlugin

#include "Basic.hpp"

#include "OpenInputPlugin_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function OpenInputPlugin.OpenInputFunctionLibrary.FillActionInfoFromRepContainer
// 0x0160 (0x0160 - 0x0000)
struct OpenInputFunctionLibrary_FillActionInfoFromRepContainer final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBPOpenVRActionInfo                    ActionInfo;                                        // 0x0010(0x00F0)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FBPSkeletalRepContainer                TargetRepContainer;                                // 0x0100(0x0058)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	uint8                                         Pad_158[0x8];                                      // 0x0158(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OpenInputFunctionLibrary_FillActionInfoFromRepContainer;

// Function OpenInputPlugin.OpenInputFunctionLibrary.FillRepContainerFromActionInfo
// 0x0150 (0x0150 - 0x0000)
struct OpenInputFunctionLibrary_FillRepContainerFromActionInfo final
{
public:
	struct FBPOpenVRActionInfo                    ActionInfo;                                        // 0x0000(0x00F0)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FBPSkeletalRepContainer                TargetRepContainer;                                // 0x00F0(0x0058)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	EVRSkeletalReplicationType                    ReplicationType;                                   // 0x0148(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OpenInputFunctionLibrary_FillRepContainerFromActionInfo;

// Function OpenInputPlugin.OpenInputFunctionLibrary.GetActionPose
// 0x0100 (0x0100 - 0x0000)
struct OpenInputFunctionLibrary_GetActionPose final
{
public:
	struct FBPOpenVRActionInfo                    Action;                                            // 0x0000(0x00F0)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UObject*                                WorldContextObject;                                // 0x00F0(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bGetCompressedData;                                // 0x00F8(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bGetGestureValues;                                 // 0x00F9(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x00FA(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_FB[0x5];                                       // 0x00FB(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OpenInputFunctionLibrary_GetActionPose;

// Function OpenInputPlugin.OpenInputFunctionLibrary.GetHandCurlAndSplayValues
// 0x0048 (0x0048 - 0x0000)
struct OpenInputFunctionLibrary_GetHandCurlAndSplayValues final
{
public:
	EVRActionHand                                 TargetHand;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBPOpenVRGesturePoseData               CurlAndSplayValuesOut;                             // 0x0008(0x0020)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UObject*                                WorldContextObject;                                // 0x0028(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OptionalCustomActionName;                          // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0040(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OpenInputFunctionLibrary_GetHandCurlAndSplayValues;

// Function OpenInputPlugin.OpenInputFunctionLibrary.GetOpenVRBoneTransform
// 0x0130 (0x0130 - 0x0000)
struct OpenInputFunctionLibrary_GetOpenVRBoneTransform final
{
public:
	EVROpenInputBones                             BoneToGet;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0xF];                                        // 0x0001(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBPOpenVRActionInfo                    HandSkeletalAction;                                // 0x0010(0x00F0)(Parm, NativeAccessSpecifierPublic)
	struct FTransform                             ReturnValue;                                       // 0x0100(0x0030)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OpenInputFunctionLibrary_GetOpenVRBoneTransform;

// Function OpenInputPlugin.OpenInputFunctionLibrary.GetReferencePose
// 0x0110 (0x0110 - 0x0000)
struct OpenInputFunctionLibrary_GetReferencePose final
{
public:
	struct FBPOpenVRActionInfo                    BlankActionToFill;                                 // 0x0000(0x00F0)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FBPOpenVRActionHandle                  ActionHandleToQuery;                               // 0x00F0(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class UObject*                                WorldContextObject;                                // 0x00F8(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EVROpenInputReferencePose                     PoseTypeToRetreive;                                // 0x0100(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0101(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_102[0xE];                                      // 0x0102(0x000E)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OpenInputFunctionLibrary_GetReferencePose;

// Function OpenInputPlugin.OpenInputFunctionLibrary.GetSkeletalTrackingLevel
// 0x0003 (0x0003 - 0x0000)
struct OpenInputFunctionLibrary_GetSkeletalTrackingLevel final
{
public:
	EVROpenInputSkeletalTrackingLevel             SkeletalTrackingLevelOut;                          // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EVRActionHand                                 HandToRetreive;                                    // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0002(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OpenInputFunctionLibrary_GetSkeletalTrackingLevel;

// Function OpenInputPlugin.OpenInputSkeletalMeshComponent.GetFingerCurlAndSplayData
// 0x0030 (0x0030 - 0x0000)
struct OpenInputSkeletalMeshComponent_GetFingerCurlAndSplayData final
{
public:
	EVRActionHand                                 TargetHand;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBPOpenVRGesturePoseData               OutFingerPoseData;                                 // 0x0008(0x0020)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0028(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OpenInputSkeletalMeshComponent_GetFingerCurlAndSplayData;

// Function OpenInputPlugin.OpenInputSkeletalMeshComponent.K2_DetectCurrentPose
// 0x0120 (0x0120 - 0x0000)
struct OpenInputSkeletalMeshComponent_K2_DetectCurrentPose final
{
public:
	struct FBPOpenVRActionInfo                    SkeletalAction;                                    // 0x0000(0x00F0)(Parm, OutParm, NativeAccessSpecifierPublic)
	struct FOpenInputGesture                      GestureOut;                                        // 0x00F0(0x0020)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0110(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_111[0xF];                                      // 0x0111(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OpenInputSkeletalMeshComponent_K2_DetectCurrentPose;

// Function OpenInputPlugin.OpenInputSkeletalMeshComponent.SaveCurrentPose
// 0x000C (0x000C - 0x0000)
struct OpenInputSkeletalMeshComponent_SaveCurrentPose final
{
public:
	class FName                                   RecordingName;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseFingerCurlOnly;                                // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EVRActionHand                                 HandToSave;                                        // 0x0009(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_OpenInputSkeletalMeshComponent_SaveCurrentPose;

// Function OpenInputPlugin.OpenInputSkeletalMeshComponent.Server_SendSkeletalTransforms
// 0x0058 (0x0058 - 0x0000)
struct OpenInputSkeletalMeshComponent_Server_SendSkeletalTransforms final
{
public:
	struct FBPSkeletalRepContainer                SkeletalInfo;                                      // 0x0000(0x0058)(ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OpenInputSkeletalMeshComponent_Server_SendSkeletalTransforms;

// Function OpenInputPlugin.OpenInputSkeletalMeshComponent.SetDetectGestures
// 0x0001 (0x0001 - 0x0000)
struct OpenInputSkeletalMeshComponent_SetDetectGestures final
{
public:
	bool                                          bNewDetectGestures;                                // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OpenInputSkeletalMeshComponent_SetDetectGestures;

// Function OpenInputPlugin.OpenInputAnimInstance.InitializeCustomBoneMapping
// 0x0040 (0x0040 - 0x0000)
struct OpenInputAnimInstance_InitializeCustomBoneMapping final
{
public:
	struct FBPSkeletalMappingData                 SkeletalMappingData;                               // 0x0000(0x0040)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_OpenInputAnimInstance_InitializeCustomBoneMapping;

}

