#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Spectator_UI

#include "Basic.hpp"


namespace SDK::Params
{

// Function Spectator_UI.Spectator_UI_C.ExecuteUbergraph_Spectator_UI
// 0x0004 (0x0004 - 0x0000)
struct Spectator_UI_C_ExecuteUbergraph_Spectator_UI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Spectator_UI_C_ExecuteUbergraph_Spectator_UI;

// Function Spectator_UI.Spectator_UI_C.SetPlayerName
// 0x0028 (0x0028 - 0x0000)
struct Spectator_UI_C_SetPlayerName final
{
public:
	class FString                                 Name_0;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0010(0x0018)()
};
DUMPER7_ASSERTS_Spectator_UI_C_SetPlayerName;

}

