#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteamVRInputDevice

#include "Basic.hpp"

#include "SteamVRInputDevice_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.FindSteamVR_Action
// 0x0058 (0x0058 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_FindSteamVR_Action final
{
public:
	class FName                                   ActionName;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bResult;                                           // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSteamVRAction                         FoundAction;                                       // 0x0010(0x0028)(Parm, OutParm, NativeAccessSpecifierPublic)
	struct FSteamVRActionSet                      FoundActionSet;                                    // 0x0038(0x0018)(Parm, OutParm, NativeAccessSpecifierPublic)
	class FName                                   ActionSet;                                         // 0x0050(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_FindSteamVR_Action;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.FindSteamVR_ActionOrigin
// 0x0014 (0x0014 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_FindSteamVR_ActionOrigin final
{
public:
	class FName                                   ActionName;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ActionSet;                                         // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_FindSteamVR_ActionOrigin;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.FindSteamVR_InputBindingInfo
// 0x0020 (0x0020 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_FindSteamVR_InputBindingInfo final
{
public:
	class FName                                   ActionName;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ActionSet;                                         // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSteamVRInputBindingInfo>       ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_FindSteamVR_InputBindingInfo;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.FindSteamVR_OriginTrackedDeviceInfo
// 0x0040 (0x0040 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_FindSteamVR_OriginTrackedDeviceInfo final
{
public:
	class FName                                   ActionName;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bResult;                                           // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSteamVRInputOriginInfo                InputOriginInfo;                                   // 0x0010(0x0028)(Parm, OutParm, NativeAccessSpecifierPublic)
	class FName                                   ActionSet;                                         // 0x0038(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_FindSteamVR_OriginTrackedDeviceInfo;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetControllerFidelity
// 0x0002 (0x0002 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetControllerFidelity final
{
public:
	EControllerFidelity                           LeftControllerFidelity;                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EControllerFidelity                           RightControllerFidelity;                           // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetControllerFidelity;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetCurlsAndSplaysState
// 0x0002 (0x0002 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetCurlsAndSplaysState final
{
public:
	bool                                          LeftHandState;                                     // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RightHandState;                                    // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetCurlsAndSplaysState;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetFingerCurlsAndSplays
// 0x002C (0x002C - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetFingerCurlsAndSplays final
{
public:
	EHand                                         hand;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSteamVRFingerCurls                    FingerCurls;                                       // 0x0004(0x0014)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FSteamVRFingerSplays                   FingerSplays;                                      // 0x0018(0x0010)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
	ESkeletalSummaryDataType                      SummaryDataType;                                   // 0x0028(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetFingerCurlsAndSplays;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetLeftHandPoseData
// 0x0030 (0x0030 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetLeftHandPoseData final
{
public:
	struct FVector                                Position;                                          // 0x0000(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Orientation;                                       // 0x000C(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                AngularVelocity;                                   // 0x0018(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Velocity;                                          // 0x0024(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetLeftHandPoseData;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetPoseSource
// 0x0001 (0x0001 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetPoseSource final
{
public:
	bool                                          bUsingSkeletonPose;                                // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetPoseSource;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetRightHandPoseData
// 0x0030 (0x0030 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetRightHandPoseData final
{
public:
	struct FVector                                Position;                                          // 0x0000(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Orientation;                                       // 0x000C(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                AngularVelocity;                                   // 0x0018(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Velocity;                                          // 0x0024(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetRightHandPoseData;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSkeletalState
// 0x0002 (0x0002 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSkeletalState final
{
public:
	bool                                          LeftHandState;                                     // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RightHandState;                                    // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSkeletalState;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSkeletalTransform
// 0x0BB0 (0x0BB0 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSkeletalTransform final
{
public:
	struct FSteamVRSkeletonTransform              LeftHand;                                          // 0x0000(0x05D0)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FSteamVRSkeletonTransform              RightHand;                                         // 0x05D0(0x05D0)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bWithController;                                   // 0x0BA0(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_BA1[0xF];                                      // 0x0BA1(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSkeletalTransform;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSteamVR_ActionArray
// 0x0010 (0x0010 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSteamVR_ActionArray final
{
public:
	TArray<struct FSteamVRAction>                 SteamVRActions;                                    // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSteamVR_ActionArray;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSteamVR_ActionSetArray
// 0x0010 (0x0010 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSteamVR_ActionSetArray final
{
public:
	TArray<struct FSteamVRActionSet>              SteamVRActionSets;                                 // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSteamVR_ActionSetArray;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSteamVR_GlobalPredictedSecondsFromNow
// 0x0004 (0x0004 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSteamVR_GlobalPredictedSecondsFromNow final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSteamVR_GlobalPredictedSecondsFromNow;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSteamVR_HandPoseRelativeToNow
// 0x0024 (0x0024 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSteamVR_HandPoseRelativeToNow final
{
public:
	struct FVector                                Position;                                          // 0x0000(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Orientation;                                       // 0x000C(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	ESteamVRHand                                  hand;                                              // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PredictedSecondsFromNow;                           // 0x001C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSteamVR_HandPoseRelativeToNow;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSteamVR_InputBindingInfo
// 0x0038 (0x0038 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSteamVR_InputBindingInfo final
{
public:
	struct FSteamVRAction                         SteamVRActionHandle;                               // 0x0000(0x0028)(Parm, NativeAccessSpecifierPublic)
	TArray<struct FSteamVRInputBindingInfo>       ReturnValue;                                       // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSteamVR_InputBindingInfo;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSteamVR_OriginLocalizedName
// 0x0048 (0x0048 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSteamVR_OriginLocalizedName final
{
public:
	struct FSteamVRAction                         SteamVRAction;                                     // 0x0000(0x0028)(Parm, NativeAccessSpecifierPublic)
	TArray<ESteamVRInputStringBits>               LocalizedParts;                                    // 0x0028(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	class FString                                 OriginLocalizedName;                               // 0x0038(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSteamVR_OriginLocalizedName;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetSteamVR_OriginTrackedDeviceInfo
// 0x0058 (0x0058 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetSteamVR_OriginTrackedDeviceInfo final
{
public:
	struct FSteamVRAction                         SteamVRAction;                                     // 0x0000(0x0028)(Parm, NativeAccessSpecifierPublic)
	struct FSteamVRInputOriginInfo                InputOriginInfo;                                   // 0x0028(0x0028)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0050(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetSteamVR_OriginTrackedDeviceInfo;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.GetUserIPD
// 0x0004 (0x0004 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_GetUserIPD final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_GetUserIPD;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.PlaySteamVR_HapticFeedback
// 0x0014 (0x0014 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_PlaySteamVR_HapticFeedback final
{
public:
	ESteamVRHand                                  hand;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StartSecondsFromNow;                               // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DurationSeconds;                                   // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Frequency;                                         // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Amplitude;                                         // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_PlaySteamVR_HapticFeedback;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.ResetSeatedPosition
// 0x0001 (0x0001 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_ResetSeatedPosition final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_ResetSeatedPosition;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.SetCurlsAndSplaysState
// 0x0002 (0x0002 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_SetCurlsAndSplaysState final
{
public:
	bool                                          NewLeftHandState;                                  // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          NewRightHandState;                                 // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_SetCurlsAndSplaysState;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.SetPoseSource
// 0x0001 (0x0001 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_SetPoseSource final
{
public:
	bool                                          bUseSkeletonPose;                                  // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_SetPoseSource;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.SetSteamVR_GlobalPredictedSecondsFromNow
// 0x0008 (0x0008 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_SetSteamVR_GlobalPredictedSecondsFromNow final
{
public:
	float                                         NewValue;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_SetSteamVR_GlobalPredictedSecondsFromNow;

// Function SteamVRInputDevice.SteamVRInputDeviceFunctionLibrary.ShowSteamVR_ActionOrigin
// 0x0040 (0x0040 - 0x0000)
struct SteamVRInputDeviceFunctionLibrary_ShowSteamVR_ActionOrigin final
{
public:
	struct FSteamVRAction                         SteamVRAction;                                     // 0x0000(0x0028)(Parm, NativeAccessSpecifierPublic)
	struct FSteamVRActionSet                      SteamVRActionSet;                                  // 0x0028(0x0018)(Parm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SteamVRInputDeviceFunctionLibrary_ShowSteamVR_ActionOrigin;

// Function SteamVRInputDevice.SteamVRTrackingReferences.ShowTrackingReferences
// 0x0010 (0x0010 - 0x0000)
struct SteamVRTrackingReferences_ShowTrackingReferences final
{
public:
	class UStaticMesh*                            TrackingReferenceMesh;                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SteamVRTrackingReferences_ShowTrackingReferences;

}

