#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteamVR

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "SteamVR_structs.hpp"
#include "InputCore_structs.hpp"


namespace SDK
{

// Class SteamVR.SteamVRChaperoneComponent
// 0x0028 (0x00D8 - 0x00B0)
class USteamVRChaperoneComponent final : public UActorComponent
{
public:
	TMulticastInlineDelegate<void()>              OnLeaveBounds;                                     // 0x00B0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnReturnToBounds;                                  // 0x00C0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_D0[0x8];                                       // 0x00D0(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	TArray<struct FVector> GetBounds() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SteamVRChaperoneComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SteamVRChaperoneComponent")
	}
	static class USteamVRChaperoneComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteamVRChaperoneComponent>();
	}
};
DUMPER7_ASSERTS_USteamVRChaperoneComponent;

// Class SteamVR.SteamVRFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class USteamVRFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool GetHandPositionAndOrientation(int32 ControllerIndex, EControllerHand hand, struct FVector* OutPosition, struct FRotator* OutOrientation);
	static bool GetTrackedDevicePositionAndOrientation(int32 DeviceID, struct FVector* OutPosition, struct FRotator* OutOrientation);
	static void GetValidTrackedDeviceIds(ESteamVRTrackedDeviceType DeviceType, TArray<int32>* OutTrackedDeviceIds);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SteamVRFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SteamVRFunctionLibrary")
	}
	static class USteamVRFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteamVRFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_USteamVRFunctionLibrary;

// Class SteamVR.SteamVRHQStereoLayerShape
// 0x0010 (0x0038 - 0x0028)
class USteamVRHQStereoLayerShape final : public UStereoLayerShapeQuad
{
public:
	bool                                          bCurved;                                           // 0x0028(0x0001)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAntiAlias;                                        // 0x0029(0x0001)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A[0x2];                                       // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         AutoCurveMinDistance;                              // 0x002C(0x0004)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AutoCurveMaxDistance;                              // 0x0030(0x0004)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetAntiAlias(bool InAntiAlias);
	void SetAutoCurveMaxDistance(float InDistance);
	void SetAutoCurveMinDistance(float InDistance);
	void SetCurved(bool InCurved);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SteamVRHQStereoLayerShape")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SteamVRHQStereoLayerShape")
	}
	static class USteamVRHQStereoLayerShape* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteamVRHQStereoLayerShape>();
	}
};
DUMPER7_ASSERTS_USteamVRHQStereoLayerShape;

}

