#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Lobby_TextField

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.ExecuteUbergraph_UI_Menu_Lobby_TextField
// 0x04C0 (0x04C0 - 0x0000)
struct UI_Menu_Lobby_TextField_C_ExecuteUbergraph_UI_Menu_Lobby_TextField final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateFontInfo                         CallFunc_Get_Font_Culture_Checked_OutFont;         // 0x0010(0x0058)(HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable_1;                            // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FEditableTextStyle                     K2Node_MakeStruct_EditableTextStyle;               // 0x0070(0x0220)()
	bool                                          Temp_bool_Variable_1;                              // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_291[0x7];                                      // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Temp_object_Variable_2;                            // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable_3;                            // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x02A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A9[0x7];                                      // 0x02A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Temp_object_Variable_4;                            // 0x02B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable_5;                            // 0x02B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsHovered;                            // 0x02C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C2[0x6];                                      // 0x02C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_Select_Default;                             // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsEnabled;                            // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x02D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_bEnable;                        // 0x02D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D3[0x1];                                      // 0x02D3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x02D4(0x0038)(IsPlainOldData, NoDestructor)
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerEvent                          K2Node_Event_MouseEvent_1;                         // 0x0310(0x0070)(ConstParm)
	struct FPointerEvent                          K2Node_Event_MouseEvent;                           // 0x0380(0x0070)(ConstParm)
	class UTexture2D*                             K2Node_Select_Default_1;                           // 0x03F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_Select_Default_2;                           // 0x03F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_ComponentBoundEvent_Text_1;                 // 0x0400(0x0018)(ConstParm)
	ETextCommit                                   K2Node_ComponentBoundEvent_CommitMethod;           // 0x0418(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_419[0x7];                                      // 0x0419(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x0420(0x0018)(ConstParm)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0438(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0460(0x0028)()
	bool                                          K2Node_Event_IsFocused;                            // 0x0488(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_489[0x7];                                      // 0x0489(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_Select_Default_3;                           // 0x0490(0x0028)()
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x04B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_ExecuteUbergraph_UI_Menu_Lobby_TextField;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.ToggleFocus
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_TextField_C_ToggleFocus final
{
public:
	bool                                          IsFocused;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_ToggleFocus;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.BndEvt__UI_Menu_Lobby_TextField_EditableText_143_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct UI_Menu_Lobby_TextField_C_BndEvt__UI_Menu_Lobby_TextField_EditableText_143_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_BndEvt__UI_Menu_Lobby_TextField_EditableText_143_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.BndEvt__UI_Menu_Lobby_TextField_EditableText_143_K2Node_ComponentBoundEvent_0_OnEditableTextCommittedEvent__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct UI_Menu_Lobby_TextField_C_BndEvt__UI_Menu_Lobby_TextField_EditableText_143_K2Node_ComponentBoundEvent_0_OnEditableTextCommittedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	ETextCommit                                   CommitMethod;                                      // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_BndEvt__UI_Menu_Lobby_TextField_EditableText_143_K2Node_ComponentBoundEvent_0_OnEditableTextCommittedEvent__DelegateSignature;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.OnMouseLeave
// 0x0070 (0x0070 - 0x0000)
struct UI_Menu_Lobby_TextField_C_OnMouseLeave final
{
public:
	struct FPointerEvent                          MouseEvent;                                        // 0x0000(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_OnMouseLeave;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.OnMouseEnter
// 0x00A8 (0x00A8 - 0x0000)
struct UI_Menu_Lobby_TextField_C_OnMouseEnter final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FPointerEvent                          MouseEvent;                                        // 0x0038(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_OnMouseEnter;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.SetEnableButton
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_TextField_C_SetEnableButton final
{
public:
	bool                                          bEnable_0;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_SetEnableButton;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_TextField_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_PreConstruct;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.ToggleEnabled
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_TextField_C_ToggleEnabled final
{
public:
	bool                                          IsEnabled;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_ToggleEnabled;

// Function UI_Menu_Lobby_TextField.UI_Menu_Lobby_TextField_C.ToggleHover
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Lobby_TextField_C_ToggleHover final
{
public:
	bool                                          IsHovered_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_Menu_Lobby_TextField_C_ToggleHover;

}

