#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_AccountPicker

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function W_AccountPicker.W_AccountPicker_C.ExecuteUbergraph_W_AccountPicker
// 0x0178 (0x0178 - 0x0000)
struct W_AccountPicker_C_ExecuteUbergraph_W_AccountPicker final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FSlateBrush& Icon)> K2Node_CreateDelegate_OutputDelegate;            // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(bool bIsSameUser)>             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFancyUserControllerSystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0040(0x0018)()
	struct FSlateBrush                            K2Node_CustomEvent_Icon;                           // 0x0058(0x0088)()
	bool                                          K2Node_CustomEvent_bIsSameUser;                    // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFancyUserControllerSystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            CallFunc_GetActiveUserIcon_ReturnValue;            // 0x00F0(0x0088)()
};
DUMPER7_ASSERTS_W_AccountPicker_C_ExecuteUbergraph_W_AccountPicker;

// Function W_AccountPicker.W_AccountPicker_C.UpdateAvatarName
// 0x0001 (0x0001 - 0x0000)
struct W_AccountPicker_C_UpdateAvatarName final
{
public:
	bool                                          bIsSameUser;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_W_AccountPicker_C_UpdateAvatarName;

// Function W_AccountPicker.W_AccountPicker_C.UpdateAvatarIcon
// 0x0088 (0x0088 - 0x0000)
struct W_AccountPicker_C_UpdateAvatarIcon final
{
public:
	struct FSlateBrush                            Icon;                                              // 0x0000(0x0088)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_W_AccountPicker_C_UpdateAvatarIcon;

}

