#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_AccountPicker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_AccountPicker.W_AccountPicker_C
// 0x0020 (0x0280 - 0x0260)
class UW_AccountPicker_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                AvatarBorder;                                      // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             UserName;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Input_Icon_C*                        W_Input_Icon;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_AccountPicker(int32 EntryPoint);
	void UpdateAvatarName(bool bIsSameUser);
	void UpdateAvatarIcon(const struct FSlateBrush& Icon);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_AccountPicker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_AccountPicker_C")
	}
	static class UW_AccountPicker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_AccountPicker_C>();
	}
};
DUMPER7_ASSERTS_UW_AccountPicker_C;

}

