#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ControllerDisonnectNotification

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_ControllerDisonnectNotification.W_ControllerDisonnectNotification_C.ExecuteUbergraph_W_ControllerDisonnectNotification
// 0x0070 (0x0070 - 0x0000)
struct W_ControllerDisonnectNotification_C_ExecuteUbergraph_W_ControllerDisonnectNotification final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x0020(0x0018)()
	bool                                          CallFunc_IsOnAnySonyPlatform_ReturnValue;          // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_1;            // 0x0040(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0058(0x0018)(ConstParm)
};
DUMPER7_ASSERTS_W_ControllerDisonnectNotification_C_ExecuteUbergraph_W_ControllerDisonnectNotification;

// Function W_ControllerDisonnectNotification.W_ControllerDisonnectNotification_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_ControllerDisonnectNotification_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_W_ControllerDisonnectNotification_C_PreConstruct;

// Function W_ControllerDisonnectNotification.W_ControllerDisonnectNotification_C.GetPlatformText
// 0x0020 (0x0020 - 0x0000)
struct W_ControllerDisonnectNotification_C_GetPlatformText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          CallFunc_IsOnAnyXboxPlatform_ReturnValue;          // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsOnAnySonyPlatform_ReturnValue;          // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_W_ControllerDisonnectNotification_C_GetPlatformText;

}

