#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ControllerDisonnectNotification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_ControllerDisonnectNotification.W_ControllerDisonnectNotification_C
// 0x0018 (0x0278 - 0x0260)
class UW_ControllerDisonnectNotification_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class URichTextBlock*                         InputText;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Title;                                   // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_ControllerDisonnectNotification(int32 EntryPoint);
	void OnControllerInput();
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	class FText GetPlatformText();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_ControllerDisonnectNotification_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_ControllerDisonnectNotification_C")
	}
	static class UW_ControllerDisonnectNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_ControllerDisonnectNotification_C>();
	}
};
DUMPER7_ASSERTS_UW_ControllerDisonnectNotification_C;

}

