#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Input_Icon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_structs.hpp"
#include "Backrooms_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Input_Icon.W_Input_Icon_C
// 0x0028 (0x0290 - 0x0268)
class UW_Input_Icon_C final : public UFancyInputIconWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0268(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Icon;                                              // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FDataTableRowHandle                    InputIcon;                                         // 0x0278(0x0010)(Edit, BlueprintVisible, NoDestructor)
	bool                                          ShowActionName;                                    // 0x0288(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_W_Input_Icon(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void OnInputDeviceChanged(EFancyInputDevice NewInputDevice);
	void UpdateIcon(EFancyInputDevice InputDevice, bool Show);
	void OnLoaded_ED0A6EA547ADA5E1277085BE13103EF7(class UObject* Loaded);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_Input_Icon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_Input_Icon_C")
	}
	static class UW_Input_Icon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Input_Icon_C>();
	}
};
DUMPER7_ASSERTS_UW_Input_Icon_C;

}

