#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TemplateTitle

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_TemplateTitle.W_TemplateTitle_C
// 0x0040 (0x02A0 - 0x0260)
class UW_TemplateTitle_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USizeBox*                               MySizeBox;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Title;                                   // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   ShowTitle;                                         // 0x0278(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          First_;                                            // 0x0290(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_291[0x3];                                      // 0x0291(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CustomHeight;                                      // 0x0294(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         CustomWidth;                                       // 0x0298(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_TemplateTitle(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void ChangeTitleColor(const struct FSlateColor& NewColorAndOpacity);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_TemplateTitle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_TemplateTitle_C")
	}
	static class UW_TemplateTitle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_TemplateTitle_C>();
	}
};
DUMPER7_ASSERTS_UW_TemplateTitle_C;

}

