#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: XRVisualization

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class XRVisualization.XRVisualizationLoadHelper
// 0x0020 (0x0048 - 0x0028)
class UXRVisualizationLoadHelper final : public UObject
{
public:
	class UStaticMesh*                            GenericHMD;                                        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UStaticMesh*                            OculusControllerMesh;                              // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UStaticMesh*                            ViveControllerMesh;                                // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UStaticMesh*                            STEMControllerMesh;                                // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("XRVisualizationLoadHelper")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"XRVisualizationLoadHelper")
	}
	static class UXRVisualizationLoadHelper* GetDefaultObj()
	{
		return GetDefaultObjImpl<UXRVisualizationLoadHelper>();
	}
};
DUMPER7_ASSERTS_UXRVisualizationLoadHelper;

// Class XRVisualization.XRVisualizationFunctionLibrary
// 0x0008 (0x0030 - 0x0028)
class UXRVisualizationFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	class UXRVisualizationLoadHelper*             LoadHelper;                                        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static void RenderHMD(const struct FXRHMDData& XRHMDData);
	static void RenderMotionController(const struct FXRMotionControllerData& XRControllerData, bool bRight);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("XRVisualizationFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"XRVisualizationFunctionLibrary")
	}
	static class UXRVisualizationFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UXRVisualizationFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UXRVisualizationFunctionLibrary;

}

